version: '3.9'
services:
  db:
    container_name: pg-container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rootPost
      POSTGRES_PASSWORD: rootPost
    ports:
      - "1234:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    
    
# volumes:
#   dbdata: